# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'baxterOsvGui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 785)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.comboBoxModeSelect = QtWidgets.QComboBox(self.groupBox_9)
        self.comboBoxModeSelect.setObjectName("comboBoxModeSelect")
        self.horizontalLayout_10.addWidget(self.comboBoxModeSelect)
        self.horizontalLayout_3.addWidget(self.groupBox_9)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.labelStatus = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatus.sizePolicy().hasHeightForWidth())
        self.labelStatus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.labelStatus.setFont(font)
        self.labelStatus.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout_11.addWidget(self.labelStatus)
        self.horizontalLayout_3.addWidget(self.groupBox_8)
        self.pushButtonQuit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonQuit.sizePolicy().hasHeightForWidth())
        self.pushButtonQuit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonQuit.setFont(font)
        self.pushButtonQuit.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButtonQuit.setObjectName("pushButtonQuit")
        self.horizontalLayout_3.addWidget(self.pushButtonQuit)
        self.horizontalLayout_3.setStretch(1, 10)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayoutGraph = QtWidgets.QVBoxLayout()
        self.verticalLayoutGraph.setObjectName("verticalLayoutGraph")
        self.horizontalLayout_12.addLayout(self.verticalLayoutGraph)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_12.addWidget(self.label_2)
        self.label_DO2 = QtWidgets.QLabel(self.groupBox)
        self.label_DO2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DO2.setObjectName("label_DO2")
        self.verticalLayout_12.addWidget(self.label_DO2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton_DO2_Up = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_DO2_Up.sizePolicy().hasHeightForWidth())
        self.pushButton_DO2_Up.setSizePolicy(sizePolicy)
        self.pushButton_DO2_Up.setObjectName("pushButton_DO2_Up")
        self.verticalLayout_15.addWidget(self.pushButton_DO2_Up)
        self.pushButton_DO2_Down = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_DO2_Down.sizePolicy().hasHeightForWidth())
        self.pushButton_DO2_Down.setSizePolicy(sizePolicy)
        self.pushButton_DO2_Down.setObjectName("pushButton_DO2_Down")
        self.verticalLayout_15.addWidget(self.pushButton_DO2_Down)
        self.horizontalLayout_7.addLayout(self.verticalLayout_15)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_13.addWidget(self.label_3)
        self.label_PEEP = QtWidgets.QLabel(self.groupBox_2)
        self.label_PEEP.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PEEP.setObjectName("label_PEEP")
        self.verticalLayout_13.addWidget(self.label_PEEP)
        self.horizontalLayout_8.addLayout(self.verticalLayout_13)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pushButton_PEEP_Up = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_PEEP_Up.sizePolicy().hasHeightForWidth())
        self.pushButton_PEEP_Up.setSizePolicy(sizePolicy)
        self.pushButton_PEEP_Up.setObjectName("pushButton_PEEP_Up")
        self.verticalLayout_16.addWidget(self.pushButton_PEEP_Up)
        self.pushButton_PEEP_Down = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_PEEP_Down.sizePolicy().hasHeightForWidth())
        self.pushButton_PEEP_Down.setSizePolicy(sizePolicy)
        self.pushButton_PEEP_Down.setObjectName("pushButton_PEEP_Down")
        self.verticalLayout_16.addWidget(self.pushButton_PEEP_Down)
        self.horizontalLayout_8.addLayout(self.verticalLayout_16)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_14.addWidget(self.label_4)
        self.label_PP = QtWidgets.QLabel(self.groupBox_3)
        self.label_PP.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PP.setObjectName("label_PP")
        self.verticalLayout_14.addWidget(self.label_PP)
        self.horizontalLayout_9.addLayout(self.verticalLayout_14)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.pushButton_PP_Up = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_PP_Up.sizePolicy().hasHeightForWidth())
        self.pushButton_PP_Up.setSizePolicy(sizePolicy)
        self.pushButton_PP_Up.setObjectName("pushButton_PP_Up")
        self.verticalLayout_17.addWidget(self.pushButton_PP_Up)
        self.pushButton_PP_Down = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_PP_Down.sizePolicy().hasHeightForWidth())
        self.pushButton_PP_Down.setSizePolicy(sizePolicy)
        self.pushButton_PP_Down.setObjectName("pushButton_PP_Down")
        self.verticalLayout_17.addWidget(self.pushButton_PP_Down)
        self.horizontalLayout_9.addLayout(self.verticalLayout_17)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        self.horizontalLayout_12.setStretch(0, 3)
        self.horizontalLayout_12.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.label_TV = QtWidgets.QLabel(self.groupBox_6)
        self.label_TV.setAlignment(QtCore.Qt.AlignCenter)
        self.label_TV.setObjectName("label_TV")
        self.verticalLayout_5.addWidget(self.label_TV)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_TV_Up = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TV_Up.sizePolicy().hasHeightForWidth())
        self.pushButton_TV_Up.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_TV_Up.setFont(font)
        self.pushButton_TV_Up.setObjectName("pushButton_TV_Up")
        self.verticalLayout_4.addWidget(self.pushButton_TV_Up)
        self.pushButton_TV_Down = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TV_Down.sizePolicy().hasHeightForWidth())
        self.pushButton_TV_Down.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_TV_Down.setFont(font)
        self.pushButton_TV_Down.setObjectName("pushButton_TV_Down")
        self.verticalLayout_4.addWidget(self.pushButton_TV_Down)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.label_IE = QtWidgets.QLabel(self.groupBox_5)
        self.label_IE.setAlignment(QtCore.Qt.AlignCenter)
        self.label_IE.setObjectName("label_IE")
        self.verticalLayout_7.addWidget(self.label_IE)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_IE_Up = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_IE_Up.sizePolicy().hasHeightForWidth())
        self.pushButton_IE_Up.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_IE_Up.setFont(font)
        self.pushButton_IE_Up.setObjectName("pushButton_IE_Up")
        self.verticalLayout_6.addWidget(self.pushButton_IE_Up)
        self.pushButton_IE_Down = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_IE_Down.sizePolicy().hasHeightForWidth())
        self.pushButton_IE_Down.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_IE_Down.setFont(font)
        self.pushButton_IE_Down.setObjectName("pushButton_IE_Down")
        self.verticalLayout_6.addWidget(self.pushButton_IE_Down)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.label_RR = QtWidgets.QLabel(self.groupBox_4)
        self.label_RR.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RR.setObjectName("label_RR")
        self.verticalLayout_9.addWidget(self.label_RR)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_RR_Up = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_RR_Up.sizePolicy().hasHeightForWidth())
        self.pushButton_RR_Up.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_RR_Up.setFont(font)
        self.pushButton_RR_Up.setObjectName("pushButton_RR_Up")
        self.verticalLayout_8.addWidget(self.pushButton_RR_Up)
        self.pushButton_RR_Down = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_RR_Down.sizePolicy().hasHeightForWidth())
        self.pushButton_RR_Down.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_RR_Down.setFont(font)
        self.pushButton_RR_Down.setObjectName("pushButton_RR_Down")
        self.verticalLayout_8.addWidget(self.pushButton_RR_Down)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButtonStart = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStart.sizePolicy().hasHeightForWidth())
        self.pushButtonStart.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonStart.setFont(font)
        self.pushButtonStart.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"")
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.verticalLayout_10.addWidget(self.pushButtonStart)
        self.pushButtonApply = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonApply.sizePolicy().hasHeightForWidth())
        self.pushButtonApply.setSizePolicy(sizePolicy)
        self.pushButtonApply.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.pushButtonApply.setObjectName("pushButtonApply")
        self.verticalLayout_10.addWidget(self.pushButtonApply)
        self.pushButtonMuteAlarm = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButtonMuteAlarm.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMuteAlarm.sizePolicy().hasHeightForWidth())
        self.pushButtonMuteAlarm.setSizePolicy(sizePolicy)
        self.pushButtonMuteAlarm.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButtonMuteAlarm.setObjectName("pushButtonMuteAlarm")
        self.verticalLayout_10.addWidget(self.pushButtonMuteAlarm)
        self.horizontalLayout_2.addWidget(self.groupBox_7)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 2)
        self.horizontalLayout_2.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 7)
        self.verticalLayout.setStretch(2, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_9.setTitle(_translate("MainWindow", "CHANGE MODE"))
        self.groupBox_8.setTitle(_translate("MainWindow", "STATUS"))
        self.labelStatus.setText(_translate("MainWindow", "NORMAL"))
        self.pushButtonQuit.setText(_translate("MainWindow", "QUIT"))
        self.groupBox.setTitle(_translate("MainWindow", "Dissolved O2"))
        self.label_2.setText(_translate("MainWindow", "MEASURED/ALARM"))
        self.label_DO2.setText(_translate("MainWindow", "<VAL>/<VAL>"))
        self.pushButton_DO2_Up.setText(_translate("MainWindow", "+"))
        self.pushButton_DO2_Down.setText(_translate("MainWindow", "-"))
        self.groupBox_2.setTitle(_translate("MainWindow", "PEEP Pressure"))
        self.label_3.setText(_translate("MainWindow", "MEASURED/ALARM"))
        self.label_PEEP.setText(_translate("MainWindow", "<VAL>/<VAL>"))
        self.pushButton_PEEP_Up.setText(_translate("MainWindow", "+"))
        self.pushButton_PEEP_Down.setText(_translate("MainWindow", "-"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Peak Pressure"))
        self.label_4.setText(_translate("MainWindow", "MEASURED/ALARM"))
        self.label_PP.setText(_translate("MainWindow", "<VAL>/<VAL>"))
        self.pushButton_PP_Up.setText(_translate("MainWindow", "+"))
        self.pushButton_PP_Down.setText(_translate("MainWindow", "-"))
        self.groupBox_6.setTitle(_translate("MainWindow", "TIDAL VOLUME"))
        self.label_6.setText(_translate("MainWindow", "CURRENT/NEW"))
        self.label_TV.setText(_translate("MainWindow", "<VAL>/<VAL>"))
        self.pushButton_TV_Up.setText(_translate("MainWindow", "+"))
        self.pushButton_TV_Down.setText(_translate("MainWindow", "-"))
        self.groupBox_5.setTitle(_translate("MainWindow", "I/E"))
        self.label_8.setText(_translate("MainWindow", "CURRENT/NEW"))
        self.label_IE.setText(_translate("MainWindow", "<VAL>/<VAL>"))
        self.pushButton_IE_Up.setText(_translate("MainWindow", "+"))
        self.pushButton_IE_Down.setText(_translate("MainWindow", "-"))
        self.groupBox_4.setTitle(_translate("MainWindow", "RESPIRATORY RATE"))
        self.label_10.setText(_translate("MainWindow", "CURRENT/NEW"))
        self.label_RR.setText(_translate("MainWindow", "<VAL>/<VAL>"))
        self.pushButton_RR_Up.setText(_translate("MainWindow", "+"))
        self.pushButton_RR_Down.setText(_translate("MainWindow", "-"))
        self.groupBox_7.setTitle(_translate("MainWindow", "CONTROL"))
        self.pushButtonStart.setText(_translate("MainWindow", "START"))
        self.pushButtonApply.setText(_translate("MainWindow", "APPLY"))
        self.pushButtonMuteAlarm.setText(_translate("MainWindow", "MUTE ALARM"))
